from typing import Dict, Literal
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from models import InsightCards, InsightCard
from .pandas_codeGenerator import run_pandas_Coder_agent
semantic_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

#Note: insight_cards are the cards generated by the LLM
#       - insight_cards: List of insight card objects
#       - schema: List of valid column names
#       - unique_insight_cards: List of unique insight card objects that has been filtered out and saved

def filter_unique_cards(state, threshold=0.7):
    """
    Filter out duplicate insight cards based on cosine similarity of questions.
    Args:
        state (dict): The current graph state
        threshold (float): Similarity threshold for filtering duplicates
    Returns:
        list: List of unique insight cards
    """
    unique_cards = []
    for idx , current_card in enumerate(state["insight_cards"]):
        duplicate = False
        
        
        duplicate=filter_question(state,current_card,mode="insight_cards",start_index=idx, threshold=threshold)
        
        if state.get("unique_insight_cards") is not None:
            duplicate=filter_question(state,current_card,mode="unique_insight_cards",start_index=idx, threshold=threshold)
        
        if not duplicate:
            unique_cards.append(current_card)
    
    return (unique_cards, len(unique_cards))

def filter_unique_Advanced_cards(state, threshold=0.7):
    """
    Filter out duplicate insight cards based on cosine similarity of questions.
    Args:
        state (dict): The current graph state
        threshold (float): Similarity threshold for filtering duplicates
    Returns:
        list: List of unique insight cards
    """
    advanced_cards = dict()
    for card in state["advanced_insight_cards"].keys():
        advanced_cards[card]=[]
        for _ , (score,ScoreAdvancedCards) in enumerate(state["advanced_insight_cards"][card]):
            duplicate = False
            # print("Filtering the Score:", score)
            for idx,current_card in enumerate(ScoreAdvancedCards):
                duplicate=filter_AdvancedCard_question(ScoreAdvancedCards,current_card,start_index=idx, threshold=threshold)
            if not duplicate:
                advanced_cards[card].append(current_card)
        advanced_cards[card]=advanced_cards[card][:15]
    
    return advanced_cards


def filter_question(state,current_card:InsightCard,mode:Literal["insight_cards","unique_insight_cards"]="insight_cards",start_index:int=0, threshold=0.7):
    """
    Filter out duplicate questions based on cosine similarity.
    Args:
        state (dict): The current graph state
        current_card (InsightCard): The current insight card to check for duplicates
        mode (str): The mode of operation ("insight_cards" or "unique_insight_cards")
        start_index (int): The starting index for filtering
        threshold (float): Similarity threshold for filtering duplicates
    Returns:
        bool: True if a duplicate is found, False otherwise
    """
    start_index = start_index +1  if mode == "insight_cards" else start_index
    duplicate = False
    for new_ques in state[mode][start_index:]:
        similarity = cosine_similarity(
            semantic_model.encode(current_card.question.lower()).reshape(1, -1),
            semantic_model.encode(new_ques.question.lower()).reshape(1, -1)
        )[0][0]
        # print(f"Comparing:\n - New: {c.question}\n - Existing: {new_ques.question}\n - Similarity: {similarity:.4f}")
        if similarity > threshold:    
            if (new_ques.breakdown).lower() == (current_card.breakdown).lower() and (new_ques.measure).lower() == (current_card.measure).lower() and (new_ques.aggregation).lower() == (current_card.aggregation).lower():
                print(f"Duplicate found: {new_ques.question} is similar to {current_card.question}")
                duplicate = True
                break
    return duplicate

def filter_AdvancedCard_question(ScoreAdvancedCards:list,current_card,start_index:int=0, threshold=0.7):
    """
    Filter out duplicate questions based on cosine similarity.
    Args:
        state (dict): The current graph state
        current_card (InsightCard): The current insight card to check for duplicates
        mode (str): The mode of operation ("insight_cards" or "unique_insight_cards")
        start_index (int): The starting index for filtering
        threshold (float): Similarity threshold for filtering duplicates
    Returns:
        bool: True if a duplicate is found, False otherwise
    """
    start_index = start_index +1  
    duplicate = False
    for new_ques in ScoreAdvancedCards[start_index:]:
        if new_ques[0]== current_card[0]:
            duplicate = True
            break
        similarity = cosine_similarity(
            semantic_model.encode(current_card[1].question.lower()).reshape(1, -1),
            semantic_model.encode(new_ques[1].question.lower()).reshape(1, -1)
        )[0][0]
        # print(f"Comparing:\n - New: {c.question}\n - Existing: {new_ques.question}\n - Similarity: {similarity:.4f}")
        if similarity > threshold:    
            if (new_ques[1].breakdown).lower() == (current_card[1].breakdown).lower() and (new_ques[1].measure).lower() == (current_card[1].measure).lower() and (new_ques[1].aggregation).lower() == (current_card[1].aggregation).lower():
                print(f"Duplicate found: {new_ques[1].question} is similar to {current_card[1].question}")
                duplicate = True
                break
    return duplicate

def validate_insight_cards_Schema(state: Dict) -> list[InsightCard]:
    """Validate insight card structure and schema compliance.

    This function checks each insight card in the state for valid schema structure and compliance,
    ensuring that breakdown columns, measure columns, and aggregation functions are valid.

    Args:
        state (Dict): A dictionary containing insight cards and schema information
            - insight_cards: List of insight card objects
            - schema: List of valid column names

    Returns:
        list[InsightCard]: List of validated insight cards that meet schema requirements

    Example:
        state = {
            "insight_cards": [card1, card2],
            "schema": ["col1", "col2"]
        }
        validated_cards = validate_insight_cards_Schema(state)

    Notes:
        - Validates if breakdown and measure columns exist in schema
        - Checks if aggregation function is one of: MIN, MAX, MEAN, COUNT, SUM, STD 
        - Invalid cards are filtered out and logged
        - Returns only the valid insight cards that pass all checks
    """
    correct_cards = []
    for card in state["insight_cards"]:
        try:
            breakdown_col = card.breakdown.lower().strip()
            measure_col = card.measure.lower().strip()
            aggregation_func = card.aggregation.strip().upper()
            # Check if breakdown and measure columns exist in the schema
            if breakdown_col not in state['schema'] or measure_col not in state['schema']:
                print(f"Invalid insight card: {card}")
                continue
            # Check if aggregation function is valid
            if aggregation_func not in ["MIN", "MAX", "MEAN", "COUNT", "SUM", "STD"]:
                print(f"Invalid aggregation function: {aggregation_func}")
                continue
            # Append valid card to correct_cards
            correct_cards.append(card)
        except Exception as e:
            print(f"Error validating insight card: {str(e)}")
            continue
    return correct_cards

async def filterationA_node(state: Dict) -> str:
    
    """
    Filteration A: Filter out invalid or duplicate insight cards.
    """
    if "insight_cards" not in state:
        raise ValueError("No insight cards provided in state.")
    # Extracting the insight cards from the state
    unique_cards, num_cards = filter_unique_cards(state)
    state["insight_cards"] = unique_cards
    state["num_cards"] = num_cards
    # Validate insight cards against schema
    valid_cards = validate_insight_cards_Schema(state)
    # Update the state with filtered cards
    state["insight_cards"] = valid_cards
    state["insight_cards"]=run_pandas_Coder_agent(state)
    print("Cards Finished from filteration A")
    return state


async def filterationB_node(state: Dict) -> str:
    """
    Filteration B: Rank insight cards based on their relevance or score.
    """
    if "advanced_insight_cards" not in state:
        raise ValueError("No advanced insight cards provided in state.")
    
    # Placeholder for ranking logic

    # For now, we will just return the insight cards as is
    # In a real implementation, you would rank the cards based on some criteria
    
    ranked_cards=filter_unique_Advanced_cards(state)

    # Update the state with ranked cards
    state["advanced_insight_cards"] = ranked_cards
    print("Cards Finished from filteration B")
    return state