FROM python:3.11.9-slim

WORKDIR /app

# Install Git
RUN apt-get update && apt-get install -y git && apt-get clean

COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

CMD ["streamlit", "run", "app.py", "--server.port", "8007"]
