from fastapi import APIRouter
from dataItems import createDashboard
from Agents.API.Services.vizServices import vizService
import json

viz_router = APIRouter()
services=vizService()

@viz_router.get('/visualizations/createDashboard',tags=["Visualizations"])
#NOTE: IRIS Endpoint AUTOGENERATED VISUALIZATION
#TODO: MAKE USER GENERATE NEW AUTOMATED VISUALIZATION IF HE WOULD LIKE (StreamLit button insertion and handling) [Kareem]
async def update_Auto_Gen_Viz(item: createDashboard):
    """
    Endpoint to retrieve visualization data for a project.

    Args:
        project_id (str): Project ID to retrieve visualization data for.

    Returns:
        dict: JSON with visualization data.
    """ 
    data_report=item.data_report
    dataframe=item.dataframe
    serializable_visualizations=await services.createVisualizations(data_report,dataframe)
    return json.dumps({'visualizations': serializable_visualizations}, allow_nan=True)