from config import *
viz_router = APIRouter()
viz_service=visualizationsService()



@viz_router.get('/project/{project_id}/visualization/update_Auto_Gen',tags=["Visualizations"])
#NOTE: IRIS Endpoint AUTOGENERATED VISUALIZATION
#TODO: MAKE USER GENERATE NEW AUTOMATED VISUALIZATION IF HE WOULD LIKE (StreamLit button insertion and handling) [Kareem]
async def update_Auto_Gen_Viz(project_id:str):
    """
    Endpoint to retrieve visualization data for a project.

    Args:
        project_id (str): Project ID to retrieve visualization data for.

    Returns:
        dict: JSON with visualization data.
    """ 
    
    checker,serializable_visualizations=await viz_service.update_Auto_Gen_Viz(project_id=project_id)
    return json.dumps({'visualizations': serializable_visualizations}, allow_nan=True)

@viz_router.get('/project/{project_id}/visualization/get_Auto_Gen',tags=["Visualizations"])
async def get_Auto_Gen_Viz(project_id:str):
    """
    Endpoint to retrieve visualization data for a project.

    Args:
        project_id (str): Project ID to retrieve visualization data for.

    Returns:
        dict: JSON with visualization data.
    """ 
    
    serializable_visualizations=await viz_service.get_Auto_Gen_Viz(project_id=project_id)
    if serializable_visualizations==[]:
        response,serializable_visualizations = await viz_service.update_Auto_Gen_Viz(project_id=project_id)
    return json.dumps({'visualizations': serializable_visualizations}, allow_nan=True)

@viz_router.get('/project/{project_id}/visualization/get_Chat_Viz',tags=["Visualizations"])
async def get_Chat_Viz(project_id:str):
    """
    Endpoint to retrieve visualization data for a project.

    Args:
        project_id (str): Project ID to retrieve visualization data for.

    Returns:
        dict: JSON with visualization data.
    """ 
    
    serializable_visualizations=await viz_service.get_Chat_Viz(project_id=project_id)
    return json.dumps({'visualizations': serializable_visualizations}, allow_nan=True)

@viz_router.post('/project/{project_id}/visualization/Chat_viz',tags=["Visualizations"])
async def Save_Chat_Viz(project_id:str,new_chat_viz:ChatViz):
    """
    Endpoint to save visualization data from generated during user chat

    Args:
        project_id (str): Project ID to retrieve visualization data for.

    Returns:
        bool: saved successfully or not
    """ 
    return await viz_service.update_Chat_Viz(project_id=project_id,new_viz=new_chat_viz)


@viz_router.get('/project/{project_id}/visualization/plot_column_type', tags=["Visualizations"])
async def plot_column_type(project_id: str):
    """
    Endpoint to plot a specific column type for a project.

    Args:
        project_id (str): Project ID to retrieve visualization data for.
        column_name (str): Column name to plot.

    Returns:
        dict: JSON with plot data.
    """
    
    plot_data = await viz_service.plot_column_types(project_id=project_id)
    return plot_data